### PR TITLE
More accessibility for dropdown

### PR DESCRIPTION
**Pull request by diiq**
Adds aria-haspopup, a title, and does a little more styling to even out the visual weight of the chevron.

### CODE REVIEW

**Comment by Allen616** [comment]
Submenu is shown deployed when opening site on iPhone. I have seen for other sites a "mobile" version of navigation that puts it in a "box." Is the chevron the preferred way to show a drop down from UX POV? I didn't understand it at first to choose the chevron for subnav.

**Comment by diiq** [comment]
Right you are. Somewhat fixed; hadn't looked at the nav on mobile, def needs some more love.

**Comment by Allen616** [comment]
Here is an example of what I was trying to explain.

**Comment by diiq** [comment]
So, just to clarify -- @oneblackcrayon's dropdown was merged last night; this PR is just to improve accessibility of the dropdown for screenreaders.

Re: is a chevron the right symbol? If you're asking "what's the right way to design a nav drop-down?" you've already heard my answer: on a simple site like this, I don't think there is one; I thought it was better without the drop-down at all. 

Re: the navigation drawer: sure, that's one way we could dress up the nav on mobile, and I'd be happy to do it, or discuss other mobile alternatives (in a different issue/PR).

**Pull request merged**
